#
# This is an example GNUmakefile for my packages
#

# specific names for this package
DICT  = lardataalg_OpT0FinderAppCint
SHLIB = liblardataalg_OpT0FinderApp.so
SOURCES = $(filter-out $(DICT).cxx, $(wildcard *.cxx))
FMWK_HEADERS = LinkDef.h $(DICT).h
HEADERS = $(filter-out $(FMWK_HEADERS), $(wildcard *.h))
OBJECTS = $(SOURCES:.cxx=.o)

# include options for this package
INCFLAGS  = -I.                       #Include itself
INCFLAGS += $(shell larlite-config --includes)
#INCFLAGS += $(shell basictool-config --includes)
#INCFLAGS += $(shell seltool-config --includes)
INCFLAGS += -I$(LARLITE_USERDEVDIR)/larcorealg
INCFLAGS += -I$(LARLITE_USERDEVDIR)/lardataalg
INCFLAGS += -I$(LARLITE_USERDEVDIR)/BasicTool
INCFLAGS += -I$(FHICLCPP_INC)
INCFLAGS += -I$(CETLIB_INC)

# platform-specific options
OSNAME          = $(shell uname -s)
HOST            = $(shell uname -n)
OSNAMEMODE      = $(OSNAME)

# call kernel specific compiler setup
include $(LARLITE_BASEDIR)/Makefile/Makefile.${OSNAME}

# call the common GNUmakefile
LDFLAGS += $(shell larlite-config --libs)
LDFLAGS += $(shell basictool-config --libs)
LDFLAGS += -L$(LARLITE_LIBDIR) -llardataalg_OpT0FinderBase
LDFLAGS += -L$(LARLITE_LIBDIR) -llardataalg_OpT0PhotonLibrary
LDFLAGS += -L$(LARLITE_LIBDIR) -llardataalg_OpT0FinderAlgorithms
include $(LARLITE_BASEDIR)/Makefile/GNUmakefile.CORE
